// src/config/swagger.js
import swaggerJsdoc from 'swagger-jsdoc';

const swaggerDefinition = {
  openapi: '3.0.3',
  info: {
    title: 'DocumentTracking API',
    version: '1.0.0',
    description: 'Autogenerated Swagger docs via swagger-jsdoc',
  },
  // Keep relative; we'll set an absolute server URL at render time to match the page origin.
  servers: [{ url: '/', description: 'Current Origin' }],
  components: { securitySchemes: {} },
};

export const swaggerOptions = {
  definition: swaggerDefinition,
  apis: ['src/routes/**/*.js', 'src/controllers/**/*.js'],
};
